In [ ]:
#Sriya kolluru
#2570123130
#Study of Numpy Library

In [ ]:
#Declaration of Numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)
print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)
print(a.dtype)
#In built function using numpy
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.eye(3))
print(np.arange(1,10,2))
print(np.linspace(0,1,4))
print(b*2)
print(a+5)
print(np.mean(a))
print(np.median(a))
print(np.max(a))

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]
1
2
(7,)
(2, 3)
int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[0.         0.33333333 0.66666667 1.        ]
[[ 2  4  6]
 [ 8 10 12]]
[  6  15  25  35  45  55 505]
93.0
30.0
500


In [ ]:
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
B = [[7,8,9],
     [4,6,5],
     [3,2,1]]
print(np.transpose(A))
print(np.dot(A,B))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 24  26  22]
 [ 66  74  67]
 [108 122 112]]
